-- Pagina Personalizada OI

-- Module insert
INSERT INTO BLC_ADMIN_MODULE (ADMIN_MODULE_ID, NAME, MODULE_KEY, ICON, DISPLAY_ORDER) VALUES (1, 'Regionalização', 'Regionalização','blc-icon-globe', 1);

-- Session Module insert
-- INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, DISPLAY_ORDER, ADMIN_MODULE_ID, NAME, SECTION_KEY, URL, CEILING_ENTITY) VALUES (1, 1, 1, 'Região', 'Região', '/regiao', 'com.oi.entidades.Regiao');

INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, CEILING_ENTITY, DISPLAY_CONTROLLER, DISPLAY_ORDER, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER, ADMIN_MODULE_ID ) VALUES (1,'com.oi.core.domains.OiRegion', NULL, 1,'Região', 'REGION', '/region', NULL, 1);

INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, CEILING_ENTITY, DISPLAY_CONTROLLER, DISPLAY_ORDER, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER, ADMIN_MODULE_ID ) VALUES (2,'com.oi.core.domains.OiCity', NULL, 1,'Cidade', 'CITY', '/city', NULL, 1);

-- PERMISSAO REGIAO
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE, IS_FRIENDLY) VALUES (1, 'Todas as Permissoes', 'PERMISSION_ALL_REGIOES', 'ALL', false);

-- Admin permission entity
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (1, 'com.oi.core.domains.OiRegion', 1);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (2, 'com.oi.core.domains.OiCity', 1);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (3, 'com.oi.core.domains.OiCityOiRegion', 1);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (4, 'com.oi.core.domains.OiProductOiRegion', 1);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (5, 'com.oi.core.domains.OiProduct', 1);


-- Section Permission
INSERT INTO BLC_ADMIN_SEC_PERM_XREF (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (1,1);
INSERT INTO BLC_ADMIN_SEC_PERM_XREF (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (2,1);

-- admin permission xref
INSERT INTO BLC_ADMIN_USER_PERMISSION_XREF (ADMIN_USER_ID, ADMIN_PERMISSION_ID) VALUES (-1, 1);